### ISSUE TITLE
Use db argument instead of pre-defined gemstone-db value in change-color function

### ISSUE THREAD

**Issue by jkottler** [PacktWorkshops/The-Clojure-Workshop#3]
https://github.com/PacktWorkshops/The-Clojure-Workshop/blob/7d50777c644e1c0133d1ab4e6105d95adf80478e/Chapter02/Exercise2.06/repl.clj#L71

I was looking through the workbook and found what appears to be an error on p.72.

In the line specified, I am almost certain the intended code was

`(assoc-in db [gemstone...` rather than `(assoc-in gemstone-db [gemstone...`

**Comment by PacktSupport** [comment]
Hello jkottler, thank you for your message. We will check this with our subject matter experts and get back to you ASAP.

**Comment by PacktSupport** [comment]
Hello jkottler, thanks for highlighting the error. We have now made the necessary changes in the code. Thanks!
